import jsPDF from "jspdf";
import type { BirthData } from "@/lib/validators/birth-data";
import type { ChartCalculationResult } from "@/types/astrology";
import type { HumanDesignChart } from "@/types/human-design";

interface ReportParams {
  birthData: BirthData;
  astroData: ChartCalculationResult;
  hdData: HumanDesignChart | null;
  readings: Record<string, string>;
  natalWheelRef: React.RefObject<HTMLDivElement | null>;
  bodygraphRef: React.RefObject<HTMLDivElement | null>;
}

// --- Constants ---
const PW = 210; // page width mm
const PH = 297; // page height mm
const ML = 20; // margin left
const MR = 20; // margin right
const MT = 22; // margin top
const CW = PW - ML - MR; // content width
const FOOTER_Y = PH - 14;
const MAX_Y = FOOTER_Y - 8; // stop text before footer

// --- Colors ---
const COL_BG: [number, number, number] = [12, 10, 26];
const COL_WHITE: [number, number, number] = [230, 230, 230];
const COL_LIGHT: [number, number, number] = [200, 200, 200];
const COL_MUTED: [number, number, number] = [150, 150, 160];
const COL_GOLD: [number, number, number] = [212, 165, 116];
const COL_GOLD_DIM: [number, number, number] = [180, 140, 100];

// --- Helpers ---

function fillBg(doc: jsPDF) {
  doc.setFillColor(...COL_BG);
  doc.rect(0, 0, PW, PH, "F");
}

function addFooter(doc: jsPDF, pageNum: number) {
  doc.setFontSize(7);
  doc.setTextColor(...COL_MUTED);
  doc.text("Generated by LightBloom Healing", ML, FOOTER_Y);
  doc.text(`${pageNum}`, PW - MR, FOOTER_Y, { align: "right" });
}

function newPage(doc: jsPDF, pn: { v: number }): number {
  addFooter(doc, pn.v);
  doc.addPage();
  pn.v++;
  fillBg(doc);
  return MT;
}

function ensureSpace(doc: jsPDF, y: number, need: number, pn: { v: number }): number {
  if (y + need > MAX_Y) return newPage(doc, pn);
  return y;
}

/**
 * Capture an SVG element inside a container as a PNG data URL.
 *
 * Strategy: clone the SVG, inline computed styles on every element,
 * serialize to XML, load as Image via Blob URL, draw to canvas, export PNG.
 *
 * Inlining computed styles is critical because serialized SVGs lose all
 * CSS class-based styling when rendered standalone in an Image element.
 */
async function captureSvg(container: HTMLElement): Promise<string | null> {
  try {
    const svgEl = container.querySelector("svg");
    if (!svgEl) {
      console.warn("[PDF] captureSvg: no <svg> found in container");
      return null;
    }

    // Get dimensions from viewBox
    const viewBox = svgEl.getAttribute("viewBox");
    const dims = viewBox ? viewBox.split(/[\s,]+/).map(Number) : [0, 0, 800, 800];
    const vbW = dims[2];
    const vbH = dims[3];

    // Clone the SVG
    const clone = svgEl.cloneNode(true) as SVGSVGElement;
    clone.setAttribute("width", String(vbW));
    clone.setAttribute("height", String(vbH));
    clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    clone.removeAttribute("class");

    // Inline computed styles on every element so the SVG is self-contained
    inlineStyles(svgEl, clone);

    // Serialize
    const svgString = new XMLSerializer().serializeToString(clone);

    // Load via Blob URL — more reliable than base64 for Unicode content
    const blob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);

    const scale = 2;
    const pngDataUrl = await loadImageToCanvas(url, vbW, vbH, scale);
    URL.revokeObjectURL(url);

    if (pngDataUrl) return pngDataUrl;

    // Fallback: try data URI with URL encoding
    const encoded = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgString)}`;
    const fallback = await loadImageToCanvas(encoded, vbW, vbH, scale);
    return fallback;
  } catch (err) {
    console.error("[PDF] captureSvg failed:", err);
    return null;
  }
}

/** Recursively inline computed styles from the live DOM onto a cloned SVG tree. */
function inlineStyles(source: Element, target: Element) {
  const computed = window.getComputedStyle(source);
  const svgStyleProps = [
    "fill", "fill-opacity", "stroke", "stroke-width", "stroke-opacity",
    "stroke-dasharray", "stroke-linecap", "stroke-linejoin",
    "opacity", "font-family", "font-size", "font-weight", "font-style",
    "text-anchor", "dominant-baseline", "color", "visibility", "display",
    "filter",
  ];
  for (const prop of svgStyleProps) {
    const val = computed.getPropertyValue(prop);
    if (val) {
      (target as SVGElement | HTMLElement).style?.setProperty(prop, val);
    }
  }

  const sourceChildren = source.children;
  const targetChildren = target.children;
  for (let i = 0; i < sourceChildren.length && i < targetChildren.length; i++) {
    inlineStyles(sourceChildren[i], targetChildren[i]);
  }
}

/** Load an image URL onto a canvas and return the PNG data URL. */
function loadImageToCanvas(
  src: string,
  w: number,
  h: number,
  scale: number
): Promise<string | null> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      try {
        const canvas = document.createElement("canvas");
        canvas.width = w * scale;
        canvas.height = h * scale;
        const ctx = canvas.getContext("2d")!;
        ctx.scale(scale, scale);
        ctx.drawImage(img, 0, 0, w, h);
        resolve(canvas.toDataURL("image/png"));
      } catch (err) {
        console.error("[PDF] canvas draw/export failed:", err);
        resolve(null);
      }
    };
    img.onerror = () => {
      console.warn("[PDF] Image failed to load from:", src.slice(0, 100));
      resolve(null);
    };
    img.src = src;
  });
}

// --- Markdown renderer ---

function renderMarkdown(doc: jsPDF, text: string, startY: number, pn: { v: number }): number {
  let y = startY;

  for (const rawLine of text.split("\n")) {
    const line = rawLine.trimEnd();

    // Empty line = paragraph spacing
    if (line === "") {
      y += 3;
      continue;
    }

    // H1
    if (line.startsWith("# ") && !line.startsWith("## ")) {
      y = ensureSpace(doc, y, 14, pn);
      y += 4;
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COL_WHITE);
      doc.text(line.slice(2), ML, y);
      y += 9;
      // Underline
      doc.setDrawColor(...COL_GOLD_DIM);
      doc.setLineWidth(0.3);
      doc.line(ML, y - 4, ML + CW, y - 4);
      continue;
    }

    // H2
    if (line.startsWith("## ") && !line.startsWith("### ")) {
      y = ensureSpace(doc, y, 12, pn);
      y += 4;
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COL_GOLD);
      doc.text(line.slice(3), ML, y);
      y += 8;
      continue;
    }

    // H3
    if (line.startsWith("### ")) {
      y = ensureSpace(doc, y, 10, pn);
      y += 3;
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COL_GOLD_DIM);
      doc.text(line.slice(4), ML, y);
      y += 7;
      continue;
    }

    // Bullet points
    const isBullet = line.startsWith("- ") || line.startsWith("* ");
    const indent = isBullet ? 5 : 0;
    const content = isBullet ? line.slice(2) : line;

    // Render text with inline bold support
    doc.setFontSize(9.5);
    doc.setTextColor(...COL_LIGHT);

    // Split bold segments: **bold** and normal text
    const segments = content.split(/(\*\*.*?\*\*)/g);
    let plainText = "";
    for (const seg of segments) {
      if (seg.startsWith("**") && seg.endsWith("**")) {
        plainText += seg.slice(2, -2);
      } else {
        plainText += seg;
      }
    }

    const wrapped = doc.splitTextToSize(plainText, CW - indent);

    for (let i = 0; i < wrapped.length; i++) {
      y = ensureSpace(doc, y, 4.5, pn);

      if (i === 0 && isBullet) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...COL_MUTED);
        doc.text("\u2022", ML + 1, y);
      }

      // For the first line, render with bold segments inline
      if (i === 0 && segments.length > 1) {
        let x = ML + indent;
        for (const seg of segments) {
          if (seg.startsWith("**") && seg.endsWith("**")) {
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...COL_WHITE);
            const t = seg.slice(2, -2);
            doc.text(t, x, y);
            x += doc.getTextWidth(t);
          } else if (seg) {
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...COL_LIGHT);
            // Only render what fits on the first wrapped line
            const availWidth = ML + indent + doc.getTextWidth(wrapped[0]) - (x - ML - indent);
            if (availWidth > 0) {
              const fitted = doc.splitTextToSize(seg, availWidth + 5)[0] || "";
              doc.text(fitted, x, y);
              x += doc.getTextWidth(fitted);
            }
          }
        }
      } else {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...COL_LIGHT);
        doc.text(wrapped[i], ML + indent, y);
      }

      y += 4.5;
    }
  }

  return y;
}

// --- Section header ---

function sectionHeader(doc: jsPDF, title: string, y: number, pn: { v: number }): number {
  y = ensureSpace(doc, y, 16, pn);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COL_WHITE);
  doc.text(title, ML, y);
  y += 4;
  doc.setDrawColor(...COL_GOLD);
  doc.setLineWidth(0.5);
  doc.line(ML, y, ML + 50, y);
  y += 8;
  return y;
}

// --- Main generator ---

export async function generateReport(params: ReportParams): Promise<void> {
  const { birthData, astroData, hdData, readings, natalWheelRef, bodygraphRef } = params;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pn = { v: 1 };

  // ===================== COVER PAGE =====================
  fillBg(doc);

  // Decorative line
  doc.setDrawColor(...COL_GOLD_DIM);
  doc.setLineWidth(0.3);
  const cx = PW / 2;
  doc.line(cx - 40, 75, cx + 40, 75);

  doc.setFontSize(38);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COL_WHITE);
  doc.text("LightBloom", cx, 88, { align: "center" });

  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COL_GOLD);
  doc.text("Healing", cx, 98, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(...COL_MUTED);
  doc.text("Astrology & Human Design Reading", cx, 112, { align: "center" });

  // Birth data
  let cy2 = 140;
  doc.setFontSize(10);
  doc.setTextColor(...COL_LIGHT);

  const infoLines = [
    `Birth Date:  ${birthData.birthDate}`,
    birthData.birthTime ? `Birth Time:  ${birthData.birthTime}` : null,
    `Location:  ${birthData.location}`,
  ].filter(Boolean) as string[];

  for (const line of infoLines) {
    doc.text(line, cx, cy2, { align: "center" });
    cy2 += 7;
  }

  if (hdData) {
    cy2 += 6;
    doc.setTextColor(...COL_GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(`${hdData.type}  \u00b7  ${hdData.authority}  \u00b7  ${hdData.profile.name}`, cx, cy2, { align: "center" });
    cy2 += 7;
    doc.setFont("helvetica", "normal");
    doc.text(`${hdData.definition} Definition`, cx, cy2, { align: "center" });
  }

  // Generation date
  doc.setFontSize(8);
  doc.setTextColor(...COL_MUTED);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    cx, PH - 30, { align: "center" }
  );

  addFooter(doc, pn.v);

  // ===================== NATAL CHART =====================
  let y = newPage(doc, pn);
  y = sectionHeader(doc, "Natal Chart", y, pn);

  // Chart image
  if (natalWheelRef.current) {
    const img = await captureSvg(natalWheelRef.current);
    if (img) {
      const imgSize = 130;
      const imgX = (PW - imgSize) / 2;
      y = ensureSpace(doc, y, imgSize + 10, pn);
      doc.addImage(img, "PNG", imgX, y, imgSize, imgSize);
      y += imgSize + 8;
    }
  }

  // Planetary positions table
  y = ensureSpace(doc, y, 8 + astroData.natal.planets.length * 4.5, pn);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COL_MUTED);
  doc.text("PLANETARY POSITIONS", ML, y);
  y += 6;

  doc.setFontSize(8.5);
  for (const p of astroData.natal.planets) {
    y = ensureSpace(doc, y, 4.5, pn);
    const retro = p.retrograde ? "  (R)" : "";
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COL_WHITE);
    doc.text(`${p.planet}${retro}`, ML + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COL_LIGHT);
    doc.text(`${p.degree}\u00b0 ${p.sign}`, ML + 38, y);
    doc.setTextColor(...COL_MUTED);
    doc.text(`House ${p.house}`, ML + 75, y);
    y += 4.5;
  }

  addFooter(doc, pn.v);

  // Natal reading
  if (readings["natal"]) {
    y = newPage(doc, pn);
    y = sectionHeader(doc, "Natal Chart Reading", y, pn);
    y = renderMarkdown(doc, readings["natal"], y, pn);
    addFooter(doc, pn.v);
  }

  // ===================== 2026 TRANSITS =====================
  if (readings["transit-2026"]) {
    y = newPage(doc, pn);
    y = sectionHeader(doc, "2026 Transit Forecast", y, pn);

    // Key transits table
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COL_MUTED);
    doc.text("KEY TRANSITS", ML, y);
    y += 6;

    doc.setFontSize(8.5);
    for (const t of astroData.transits2026.slice(0, 20)) {
      y = ensureSpace(doc, y, 4.5, pn);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COL_GOLD_DIM);
      doc.text(t.date, ML + 2, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COL_LIGHT);
      const desc = t.transitPlanet === "Event"
        ? t.description
        : `${t.transitPlanet} ${t.aspectType} ${t.natalPlanet}`;
      doc.text(desc, ML + 30, y);
      y += 4.5;
    }

    addFooter(doc, pn.v);

    // Transit reading
    y = newPage(doc, pn);
    y = sectionHeader(doc, "2026 Forecast Reading", y, pn);
    y = renderMarkdown(doc, readings["transit-2026"], y, pn);
    addFooter(doc, pn.v);
  }

  // ===================== HUMAN DESIGN =====================
  if (hdData && readings["human-design"]) {
    y = newPage(doc, pn);
    y = sectionHeader(doc, "Human Design", y, pn);

    // Bodygraph image
    if (bodygraphRef.current) {
      const img = await captureSvg(bodygraphRef.current);
      if (img) {
        const imgW = 90;
        const imgH = 140;
        const imgX = (PW - imgW) / 2;
        y = ensureSpace(doc, y, imgH + 10, pn);
        doc.addImage(img, "PNG", imgX, y, imgW, imgH);
        y += imgH + 8;
      }
    }

    // HD properties
    y = ensureSpace(doc, y, 40, pn);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COL_MUTED);
    doc.text("CHART PROPERTIES", ML, y);
    y += 6;

    const props = [
      ["Type", hdData.type],
      ["Authority", hdData.authority],
      ["Profile", hdData.profile.name],
      ["Definition", hdData.definition],
      ["Incarnation Cross", hdData.incarnationCross.name],
    ];

    doc.setFontSize(9);
    for (const [label, value] of props) {
      y = ensureSpace(doc, y, 5.5, pn);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COL_MUTED);
      doc.text(`${label}:`, ML + 2, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COL_GOLD);
      doc.text(value, ML + 45, y);
      y += 5.5;
    }

    addFooter(doc, pn.v);

    // HD reading
    y = newPage(doc, pn);
    y = sectionHeader(doc, "Human Design Reading", y, pn);
    y = renderMarkdown(doc, readings["human-design"], y, pn);
    addFooter(doc, pn.v);
  }

  // ===================== SYNTHESIS =====================
  if (readings["synthesis"]) {
    y = newPage(doc, pn);
    y = sectionHeader(doc, "Integrated Synthesis", y, pn);
    y = renderMarkdown(doc, readings["synthesis"], y, pn);
    addFooter(doc, pn.v);
  }

  // ===================== NEXT STEPS =====================
  y = newPage(doc, pn);
  y = sectionHeader(doc, "Next Steps", y, pn);

  y += 2;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COL_LIGHT);

  const nextStepsText = [
    "Your chart reveals a rich and unique cosmic blueprint. While this report provides",
    "a comprehensive overview, a personal consultation can help you:",
  ];
  for (const line of nextStepsText) {
    doc.text(line, ML, y);
    y += 5.5;
  }

  y += 4;
  const bullets = [
    "Understand the deeper patterns between your natal placements",
    "Navigate upcoming transits with practical, personalized strategies",
    "Explore how your Human Design type shapes your daily decisions",
    "Identify the most impactful areas for growth in the year ahead",
  ];

  doc.setFontSize(10);
  for (const bullet of bullets) {
    doc.setTextColor(...COL_MUTED);
    doc.text("\u2022", ML + 4, y);
    doc.setTextColor(...COL_LIGHT);
    doc.text(bullet, ML + 10, y);
    y += 6;
  }

  y += 8;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COL_GOLD);
  doc.text("Book a Personal Consultation", ML, y);

  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COL_LIGHT);
  doc.text("Visit www.lightbloomhealing.com to schedule a session,", ML, y);
  y += 5.5;
  doc.text("view pricing, or get in touch directly.", ML, y);

  // Bottom tagline
  doc.setFontSize(8);
  doc.setTextColor(...COL_MUTED);
  doc.text(
    "lightbloomhealing.com \u2022 Astrology & Human Design, Illuminated by AI",
    cx,
    PH - 30,
    { align: "center" }
  );

  addFooter(doc, pn.v);

  // Save
  const filename = `lightbloom-healing-${birthData.birthDate}.pdf`;
  doc.save(filename);
}
